/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsClientIdIndexRouteImport } from './routes/clients.$clientId.index'
import { Route as ClientsClientIdLogRouteImport } from './routes/clients.$clientId.log'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdIndexRoute = ClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const ClientsClientIdLogRoute = ClientsClientIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ClientsClientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/schedule': typeof ScheduleRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/clients/$clientId/log': typeof ClientsClientIdLogRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/schedule': typeof ScheduleRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/clients/$clientId/log': typeof ClientsClientIdLogRoute
  '/clients/$clientId': typeof ClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/schedule': typeof ScheduleRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/clients/$clientId/log': typeof ClientsClientIdLogRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/portal'
    | '/schedule'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/log'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/portal'
    | '/schedule'
    | '/clients/new'
    | '/clients'
    | '/clients/$clientId/log'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/login'
    | '/portal'
    | '/schedule'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/log'
    | '/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  ScheduleRoute: typeof ScheduleRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/': {
      id: '/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof ClientsClientIdIndexRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/clients/$clientId/log': {
      id: '/clients/$clientId/log'
      path: '/log'
      fullPath: '/clients/$clientId/log'
      preLoaderRoute: typeof ClientsClientIdLogRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdLogRoute: typeof ClientsClientIdLogRoute
  ClientsClientIdIndexRoute: typeof ClientsClientIdIndexRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdLogRoute: ClientsClientIdLogRoute,
  ClientsClientIdIndexRoute: ClientsClientIdIndexRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  ScheduleRoute: ScheduleRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
