/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsClientIdIndexRouteImport } from './routes/clients.$clientId.index'
import { Route as ClientsClientIdLogRouteImport } from './routes/clients.$clientId.log'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdIndexRoute = ClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const ClientsClientIdLogRoute = ClientsClientIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ClientsClientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/$clientId/log': typeof ClientsClientIdLogRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/$clientId/log': typeof ClientsClientIdLogRoute
  '/clients/$clientId': typeof ClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/$clientId/log': typeof ClientsClientIdLogRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/$clientId/log'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clients/new'
    | '/clients/$clientId/log'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/$clientId/log'
    | '/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/': {
      id: '/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof ClientsClientIdIndexRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/clients/$clientId/log': {
      id: '/clients/$clientId/log'
      path: '/log'
      fullPath: '/clients/$clientId/log'
      preLoaderRoute: typeof ClientsClientIdLogRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdLogRoute: typeof ClientsClientIdLogRoute
  ClientsClientIdIndexRoute: typeof ClientsClientIdIndexRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdLogRoute: ClientsClientIdLogRoute,
  ClientsClientIdIndexRoute: ClientsClientIdIndexRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
